# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=1.21
	yarn_mappings=1.21+build.9
	loader_version=0.16.2

# Mod Properties
	mod_version = 1.0.0-1.21
	maven_group = com.minenash
	archives_base_name = soulguard

# Dependencies
	# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
	fabric_version=0.102.0+1.21
	trinkets_version=3.10.0
	mod_menu_version=9.0.0-pre.1
	cca_version=6.1.0
